version: '0.2'
sources:
- database: local
  link: ''
  type: local
  branch: master
  cache_path: ''
  cache_timestamp: ''
  filters: null
- database: poo
  link: https://github.com/qxcodepoo/arcade.git
  type: clone
  branch: master
  cache_path: ''
  cache_timestamp: '2025-12-11 07:26:57'
  filters:
  - herança
expanded:
- poo@campanha-principal
- poo@bloco_f-herança-i
tasks:
  poo@zoo: '{rate:100, alone:10, study:160}'
  poo@shapes: '{rate:100, alone:9, study:180}'
  poo@estacionamento: '{rate:100, iagen:deepseek, alone:8, study:250}'
flags:
  quests: 1
  tracks: 0
  tasks: 0
  graph: 1
  xray: 0
lang: py
selected: poo@estacionamento
